services:
  mocksocket-server:
    build:
      context: ..
      dockerfile: docker-setup/Dockerfile
    image: mocksocket-server:local
    ports:
      - "7896:7896"
    environment:
      - PORT=7896
